services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    ports:
      - "80:80"       # Graphite web interface
      - "2003-2004:2003-2004" # Carbon receivers
      - "2023-2024:2023-2024" # Graphite web monitoring
      - "8125:8125/udp" # StatsD UDP port
      - "8126:8126"     # StatsD admin port

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000" # Grafana web interface
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password
    depends_on:
      - graphite
    volumes:
      - ./provisioning:/etc/grafana/provisioning

volumes:
  provisioning:
    driver: local